### ISSUE TITLE
500 on `person_add_requests`

### ISSUE THREAD

**Issue by yannbolliger** [hitobito/hitobito_pbs#228] opened 2022-06-01 15:30 UTC
Since the latest release we get a 500 on this page:
`https://db.scout.ch/de/groups/374/person_add_requests`

We also get a 500 if we try to change the settings of this group.

**Comment by carlobeltrame** [comment] 2022-06-02 06:43
Thanks for the report! We'll look into it. It's not a general problem, on other groups the same view still works. Sentry issue for internal reference: 
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/53932

What exactly do you mean by "updating the group settings"? If it's only changing the group logo, we're already working on a fix for that. If it's something else, please describe exactly how to reproduce.

**Comment by yannbolliger** [comment] 2022-06-02 07:03
It was changing the group logo 👍

**Comment by kronn** [comment] 2022-06-07 11:20
The errors should be fixed now. Both the one mentioned by @carlobeltrame and the one caused by uploading the group-logo. Sorry for the inconvenience, enjoy version 1.27.24 :-)

**Closed by kronn** 2022-06-07 11:20 UTC
